name: material2_dart
description: A personal experiment to port angular/material2 to the Dart version.
version: 0.0.1
author: ntaoo <ntaoo.g@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.0.0-beta.17
  stack_trace: any

dev_dependencies:
  browser: ^0.10.0
  test: '>=0.12.0 <0.13.0'
  angular2_testing: any
  quiver: '^0.21.4'
  scissors: ^0.6.1

transformers:
- scissors:
    verbose: true
    pruneCss: false
- angular2
- test/pub_serve:
    $include: test/**_test{.*,}.dart