name: material2_dart
description: Experimental angular/material2 Dart version.
version: 0.0.3
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/material2_dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.0.0-beta.17
  http: ^0.11.3
  stack_trace: any
  stream_transformers: ^0.3.0
  quiver: '^0.21.4'

dev_dependencies:
  browser: ^0.10.0
  test: '>=0.12.0 <0.13.0'
  angular2_testing: any
  scissors: ^0.6.1

transformers:
- scissors:
    verbose: true
    pruneCss: false
- angular2
- test/pub_serve:
    $include: test/**_test{.*,}.dart